PHP Workflow File Sync [Runner ID: 38]

diff --git a/.github/workflows/test-phpunit.yml b/.github/workflows/test-phpunit.yml
--- a/.github/workflows/test-phpunit.yml
+++ b/.github/workflows/test-phpunit.yml
@@ -24,6 +24,11 @@ concurrency:
 
 jobs:
 
+  ###
+  #
+  # Setup the test matrix.
+  #
+  ###
   set-matrix:
     name: Setup Matrix
     runs-on: ubuntu-latest
@@ -34,6 +39,11 @@ jobs:
       - id: setup
         uses: gocodebox/.github/.github/actions/setup-matrix@trunk
 
+  ###
+  #
+  # Run tests.
+  #
+  ###
   test:
     name: WP ${{ matrix.WP }} on PHP ${{ matrix.PHP }}${{ matrix.name-append }}
 
@@ -59,7 +69,26 @@ jobs:
           env-file: ".github/.env.test-phpunit"
           secrets: ${{ toJSON( secrets ) }}
 
-      # Run Tests.
       - name: Run Tests
         run: composer run tests
 
+  ###
+  #
+  # Check the status of the entire test matrix.
+  #
+  # This will succeed if all jobs from the `test` job's matrix succeed. It allows jobs marked with `allow-failure`
+  # to fail.
+  #
+  # This job can be used as a single status check for branch protection rules. Without this
+  # we would need to require every job in the above build matrix.
+  #
+  ###
+  status:
+    name: Test PHPUnit Status
+    runs-on: ubuntu-latest
+    if: ${{ always() }}
+    needs: test
+    steps:
+      - name: Check overall matrix status
+        if: ${{ 'success' != needs.test.result }}
+        run: exit 1
